import styles from "../../styles/HelpCenter.module.css";
import Link from "next/link";
import Faqs from "./Faqs";
import Navigation from '../includes/Navigation';
import Footer from '../includes/Footer';
import HelpCenterList from "./HelpCenterList";
import MobilePanel from "./MobilePanel";
import Head from "next/head";
import ContactForm from "./ContactForm";

export default function Contact() {
    return (
        <>

            <Head>
                <meta name="description" content="Generated by Bizsapp" />
                <link rel="icon" href="/img/favicon.svg" />
                <title>BizsApp | The Business App</title>
            </Head>

            <Navigation />
            <div className="container">
                <div className="row">
                    <div className="col-xl-4 col-lg-4 col-md-4 col-sm-12 col-12">
                        <div className={styles.left_panel}>
                            <div className="left_accordion">

                                <div className="accordion accordion-flush" id="accordionFlushExample">
                                    <div className="accordion-item">
                                        <h2 className="accordion-header" id="flush-headingOne">
                                            <button className="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#flush-faqs" aria-expanded="false" aria-controls="flush-faqs">
                                                <img src="/img/icons/chat.png" alt="chat" className="img-fluid" />  BizsApp FAQ's
                                            </button>
                                        </h2>
                                        <div id="flush-faqs" className="accordion-collapse collapse" aria-labelledby="flush-headingOne" data-bs-parent="#accordionFlushExample">
                                            <div className="accordion-body">
                                                <Faqs />
                                            </div>
                                        </div>
                                    </div>
                                </div>

                                <HelpCenterList />

                            </div>
                        </div>
                        {/* ==========mobile tabs====== */}
                        <MobilePanel />
                    </div>
                    <div className="col-xl-8 col-lg-8 col-md-8 col-sm-12 col-12">
                        <div className={styles.page_content}>
                            <div className={styles.page_name}>
                                <h2>Contact</h2>
                            </div>
                            <ContactForm />
                        </div>
                        
                    </div>
                </div>
            </div>

            <Footer />
        </>
    )
};
