import styles from '../../../styles/HelpCenter.module.css';
import Navigation from '../../includes/Navigation';
import Footer from '../../includes/Footer';
import Faqs from '../Faqs';
import HelpCenterList from '../HelpCenterList';
import MobilePanel from '../MobilePanel';
import RequestQna from './RequestQna';
import Head from 'next/head';

export default function Request() {
    return (
        <>
            <Head>
                <meta name="description" content="Generated by Bizsapp" />
                <link rel="icon" href="/img/favicon.svg" />
                <title>BizsApp | The Business App</title>
            </Head>
            <Navigation />


            <div className="container">
                <div className="row">
                    <div className="col-xl-4 col-lg-4 col-md-4 col-sm-12 col-12">
                        <div className={styles.left_panel}>
                            <div className="left_accordion">
                                <div className="accordion" id="accordionExample">
                                    <div className="accordion-item">
                                        <h2 className="accordion-header" id="headingFaqsOne">
                                            <button className="accordion-button" type="button" data-bs-toggle="collapse" data-bs-target="#faqs" aria-expanded="true" aria-controls="faqs">
                                                <img src="/img/icons/chat.png" alt="chat" className="img-fluid" />  BizsApp FAQ's
                                            </button>
                                        </h2>
                                        <div id="faqs" className="accordion-collapse collapse show" aria-labelledby="headingFaqsOne" data-bs-parent="#accordionExample">
                                            <div className="accordion-body">
                                                <Faqs />
                                            </div>
                                        </div>
                                    </div>

                                </div>
                            </div>
                            <HelpCenterList />
                        </div>
                        {/* ==========mobile tabs====== */}
                        <MobilePanel />
                    </div>
                    <div className="col-xl-8 col-lg-8 col-md-8 col-sm-12 col-12">
                        <div className={styles.page_content}>
                            <div className={styles.page_name}>
                                <h2>Request</h2>
                            </div>
                            <RequestQna />
                        </div>
                    </div>
                </div>
            </div>

            <Footer />
        </>
    )
};
