import React, { useEffect, useState } from "react"
import styles from '../../styles/BMCUserCard.module.css';
import Head from 'next/head'
import { Swiper, SwiperSlide } from "swiper/react";
import Image from "next/image";

// Import Swiper styles
import "swiper/css";
import "swiper/css/effect-coverflow";
import "swiper/css/pagination";
// import required modules
import { EffectCoverflow, Pagination } from "swiper";
import ReactPlayer from 'react-player'
import { pageURL } from "../../utils/PageURL";

export default function UserCard(data) {


    const [cardData, setCardData] = useState()

    useEffect(() => {
        setCardData(data.data.data)
        console.log("cardData", cardData)
    }, [])


    const [active, setActive] = useState(false);
    const [isActive, setIsActive] = useState(false)
    const [isProduct, setIsProduct] = useState(false)
    const [selectProduct, setSelectProduct] = useState()

    const handleModal = () => {
        setIsActive(!isActive)
    }

    const handleProduct = (e) => {
        setIsProduct(true)
        setSelectProduct(e)
    }

    const [copied, setCopied] = useState(false);
    function copy() {
        const el = document.createElement("input");
        el.value = window.location.href;
        document.body.appendChild(el);
        document.body.appendChild(el);
        el.select();
        document.execCommand("copy");
        document.body.removeChild(el);
        setCopied(true);
    }

    return (
        <>
            <Head>
                <title>{`${cardData?.brandName} BMC | Business Management Card`}</title>
                <meta name="description" content="Generated by Bizsapp" />
                <link rel="icon" href="/favicon.ico" />
                <meta name="msapplication-TileImage" content={cardData?.brandLogo} />
                <meta property="og:site_name" content={cardData?.brandName} />
                <meta property="og:BMC" content={cardData?.address} />
                <meta property="og:title Card" content="Business Managment Card" />
                <meta property="og:image" itemprop="image" content={cardData?.brandLogo} />
                <meta property="og:type" content="website" />
                <meta property="og:image:type" content="image/png" />
                <meta property="og:image:width" content="300" />
                <meta property="og:image:height" content="300" />
                <meta property="og:url" content="bizsapp.com" />
            </Head>



            <section className='container-fluid p-0'>
                <div className={styles.bmc_box}>
                    <div className={styles.flip_card}>
                        <div className={active ? `${styles.card} ${styles.active}` : styles.card}>
                            {/* fornt side */}
                            <div className={`${styles.card__face} ${styles.card__face_front}`} style={{ backgroundImage: `linear-gradient(to top, #${cardData?.theme?.dark} , #${cardData?.theme?.light})` }}>
                                <div className={styles.cardFrontContent}>
                                    <div className={styles.cardName}>
                                        Business Management Card
                                        <div className="cardShareBtn">
                                            <img src="/img/ecard/menu.png" alt="share" className='img-fluid' data-bs-toggle="offcanvas" data-bs-target="#offcanvasBottom" aria-controls="offcanvasBottom" />
                                        </div>
                                    </div>

                                    <div className={styles.forntProfileBox}>
                                        <div className={styles.companyLogo}>
                                            <img src={cardData?.brandLogo} className="img-fluid" />
                                        </div>
                                        <div className={styles.companyName}>
                                            <h1>{cardData?.brandName}</h1>
                                        </div>
                                        <div className={styles.designationName}>
                                            <span>({cardData?.user?.title})</span>
                                        </div>
                                        <div className={styles.descriptionBox}>
                                            <p>{cardData?.about}</p>
                                        </div>
                                    </div>

                                    <div className={styles.catalogBox}>
                                        <div className={styles.catalogTitle}>
                                            <div>My Catalogue</div>
                                        </div>
                                        <div className="catalogSlider">
                                            <Swiper
                                                slidesPerView={"auto"}
                                                spaceBetween={10}
                                                pagination={{
                                                    clickable: true,
                                                }}
                                                modules={[Pagination]}
                                                className="mySwiper"
                                            >
                                                {cardData?.products && cardData?.products?.map((curElt) => {
                                                    return (
                                                        <>
                                                            <SwiperSlide>
                                                                <div className={styles.prouctSliderBox} >
                                                                    <div className={styles.productImg}>
                                                                        {curElt.images && curElt.images?.map((productImg, index) => {
                                                                            if (index <= 1) {
                                                                                return (
                                                                                    <>
                                                                                        <img src={productImg.location} onClick={() => handleProduct(curElt)} alt='catalog_image' className='img-fluid' />
                                                                                    </>
                                                                                )
                                                                            }
                                                                        })}
                                                                        {/* <img src='/img/ecard/product1.png' alt='catalog_image' className='img-fluid' /> */}
                                                                    </div>
                                                                    <div className={styles.productName}>
                                                                        <p>{curElt.title}</p>
                                                                    </div>
                                                                </div>
                                                            </SwiperSlide>
                                                        </>
                                                    )
                                                })}
                                            </Swiper>
                                        </div>
                                    </div>

                                    <div className={styles.bottomButtonBox}>

                                        <ul>
                                            <li>
                                                <div className={styles.iconBox}>
                                                    <a href={`tel:+91${cardData?.contacts[0]?.contactNumber}`}>
                                                        <img src="/img/ecard/phone.png" alt="phone" className='img-fluid' />
                                                    </a>
                                                </div>
                                            </li>
                                            <li>
                                                <div className={styles.iconBox}>
                                                    <a href={`https://wa.me/+91${cardData?.contacts[1]?.contactNumber}?text=Hello ${cardData?.brandName}`} target="_blank">
                                                        <img src="/img/ecard/whatsapp.png" alt="whatsapp" className='img-fluid' />
                                                    </a>
                                                </div>
                                            </li>
                                            <li>
                                                <div className={`${styles.iconBox}  ${styles.linkIcon}`}>
                                                    <img src="/img/ecard/linkBig.png" alt="link" className='img-fluid' />
                                                </div>
                                            </li>
                                            <li>
                                                <div className={styles.iconBox}>
                                                    <img src="/img/ecard/bizsicon.png" alt="mail" className='img-fluid' />
                                                </div>
                                            </li>
                                            <li>
                                                <div className={styles.iconBox} onClick={() => setActive(!active)}>
                                                    <img src="/img/ecard/next.png" alt="arow" className='img-fluid' />
                                                </div>
                                            </li>
                                        </ul>
                                    </div>
                                </div>
                                {/* =======share modal====== */}
                                <div className={isActive ? "shareModalBoxOpen" : "null"}>
                                    <div className={`${styles.iconBox} openShareModal`} onClick={handleModal}>
                                        <img src="/img/ecard/linkBig.png" alt="link" className='img-fluid' />
                                        <img src="/img/ecard/close.png" alt="link" className='img-fluid' />
                                    </div>
                                    <div className="shareModalBox">
                                        <ul>
                                            <li>
                                                <a href="#">

                                                    <img src="/img/ecard/chat.png" alt="arow" className='img-fluid' />

                                                </a>
                                            </li>
                                            {cardData?.socialLinks && cardData?.socialLinks?.map((curElt) => {
                                                return (
                                                    <>
                                                        {curElt.socialLinkType === "Facebook" &&
                                                            <li>
                                                                <a href={curElt.link} target="_blank">
                                                                    <div><img src="/img/ecard/link.png" alt="arow" className='img-fluid' /></div>
                                                                    <div>Facebook</div>
                                                                </a>
                                                            </li>

                                                        }
                                                        {curElt.socialLinkType === "Instagram" &&
                                                            <li>
                                                                <a href={curElt.link} target="_blank">

                                                                    <div><img src="/img/ecard/link.png" alt="arow" className='img-fluid' /></div>
                                                                    <div>Instagram</div>

                                                                </a>
                                                            </li>
                                                        }
                                                        {curElt.socialLinkType === "Youtube" &&
                                                            <li>
                                                                <a href={curElt.link} target="_blank">

                                                                    <div><img src="/img/ecard/link.png" alt="arow" className='img-fluid' /></div>
                                                                    <div>YouTube</div>

                                                                </a>
                                                            </li>
                                                        }
                                                        {curElt.socialLinkType === "LinkedIn" &&
                                                            <li>
                                                                <a href={curElt.link} target="_blank">

                                                                    <div><img src="/img/ecard/link.png" alt="arow" className='img-fluid' /></div>
                                                                    <div>Linkedin</div>

                                                                </a>
                                                            </li>

                                                        }
                                                        {curElt.socialLinkType === "Twitter" &&
                                                            <li>
                                                                <a href={curElt.link} target="_blank">
                                                                    <div><img src="/img/ecard/link.png" alt="arow" className='img-fluid' /></div>
                                                                    <div> Twitter</div>
                                                                </a>
                                                            </li>
                                                        }
                                                    </>
                                                )
                                            })}
                                            {cardData?.websiteLink &&

                                                <li>
                                                    <a href={cardData?.websiteLink} target="_blank">
                                                        <div><img src="/img/ecard/link.png" alt="arow" className='img-fluid' /></div>
                                                        <div>Website</div>
                                                    </a>
                                                </li>

                                            }
                                        </ul>
                                    </div>
                                </div>
                                {/* =======end====== */}
                                {/* ========product modal===== */}
                                <div className={isProduct ? "productModalBoxOpen" : "null"}>
                                    <div className="productModalBox" >
                                        <div className="productModalContent">

                                            <img src="/img/ecard/closeWhite.png" alt="closeWhite" className='img-fluid' onClick={() => setIsProduct("")} />
                                            {console.log("product data ", selectProduct)}
                                            <div className={styles.selectProductTitle}>
                                                <p>{selectProduct ? selectProduct?.title : ''}</p>
                                            </div>
                                            <Swiper
                                                slidesPerView={"auto"}
                                                spaceBetween={30}
                                                pagination={{
                                                    clickable: true,
                                                }}
                                                modules={[Pagination]}
                                                className="ProductSwiper"
                                            >
                                                {selectProduct ?


                                                    <div className={styles.prouctSliderBox} >
                                                        {selectProduct?.images && selectProduct?.images?.map((curEltImg) => {
                                                            return (
                                                                <>
                                                                    <SwiperSlide>
                                                                        <div className="productSliderBox">
                                                                            <img src={curEltImg.location} />
                                                                        </div>
                                                                    </SwiperSlide>
                                                                </>
                                                            )
                                                        })}
                                                    </div>


                                                    :

                                                    ''

                                                }
                                            </Swiper>
                                            {selectProduct ?
                                                <>
                                                    <div className={styles.productPrice}>
                                                        <p><img src="/img/ecard/rupee.png" alt="arow" className='img-fluid' /> {selectProduct ? selectProduct.price : ''}</p>
                                                    </div>
                                                    <div className={styles.productDesc}>
                                                        <h4>Service Description</h4>
                                                        {selectProduct?.description}
                                                    </div>
                                                    <div className={styles.productConnectBtn}>
                                                        <button>Start Chat</button>
                                                    </div>
                                                </>

                                                :

                                                ""
                                            }


                                        </div>
                                    </div>
                                </div>
                                {/* ======end======= */}
                            </div>
                            {/* back side */}
                            <div className={`${styles.card__face} ${styles.card__face_back}`} style={{ backgroundImage: `linear-gradient(to top, #${cardData?.theme?.dark} , #${cardData?.theme?.light})` }}>
                                <div className={styles.cardBackContent}>
                                    <div className={styles.cardName}>
                                        Business Management Card
                                        <div className="cardShareBtn">
                                            <img src="/img/ecard/menu.png" alt="share" className='img-fluid' data-bs-toggle="offcanvas" data-bs-target="#offcanvasBottom" aria-controls="offcanvasBottom" />
                                        </div>
                                    </div>
                                    <div className={styles.cardVideoBox}>
                                        <div className="cardVideo">
                                            <ReactPlayer
                                                url={cardData?.brandVideo?.location ? cardData?.brandVideo?.location : cardData?.brandVideo?.link}
                                                controls
                                                config={{ file: { attributes: { controlsList: 'nodownload' } } }}
                                                onContextMenu={(e) => e.preventDefault()}
                                            />
                                            <div className={styles.cardVideoTitle}>
                                                {cardData?.brandVideo?.videoTitle}
                                            </div>
                                        </div>
                                    </div>
                                    <div className={styles.cardDateTimeBox}>
                                        <div className="cardDataTime">
                                            <h2>Day & Time</h2>
                                            <div className={styles.dateTimeContent}>
                                                <h4>{cardData?.businessTiming}</h4>
                                                <ul>
                                                    {cardData?.businessDays.includes('monday') ?

                                                        (
                                                            <>
                                                                <li><p>MO</p></li>
                                                            </>
                                                        )

                                                        :

                                                        (
                                                            <>
                                                                <li className={styles.disable}><p>MO</p></li>
                                                            </>
                                                        )

                                                    }

                                                    {cardData?.businessDays.includes('tuesday') ?

                                                        (
                                                            <>
                                                                <li><p>TU</p></li>
                                                            </>
                                                        )

                                                        :

                                                        (
                                                            <>
                                                                <li className={styles.disable}><p>TU</p></li>
                                                            </>
                                                        )

                                                    }

                                                    {cardData?.businessDays.includes('wednesday') ?

                                                        (
                                                            <>
                                                                <li><p>WE</p></li>
                                                            </>
                                                        )

                                                        :

                                                        (
                                                            <>
                                                                <li className={styles.disable}><p>WE</p></li>
                                                            </>
                                                        )

                                                    }


                                                    {cardData?.businessDays.includes('thursday') ?

                                                        (
                                                            <>
                                                                <li><p>TH</p></li>
                                                            </>
                                                        )

                                                        :

                                                        (
                                                            <>
                                                                <li className={styles.disable}><p>TH</p></li>
                                                            </>
                                                        )

                                                    }

                                                    {cardData?.businessDays.includes('friday') ?

                                                        (
                                                            <>
                                                                <li><p>FR</p></li>
                                                            </>
                                                        )

                                                        :

                                                        (
                                                            <>
                                                                <li className={styles.disable}><p>FR</p></li>
                                                            </>
                                                        )

                                                    }

                                                    {cardData?.businessDays.includes('saturday') ?

                                                        (
                                                            <>
                                                                <li><p>SA</p></li>
                                                            </>
                                                        )

                                                        :

                                                        (
                                                            <>
                                                                <li className={styles.disable}><p>SA</p></li>
                                                            </>
                                                        )

                                                    }

                                                    {cardData?.businessDays.includes('sunday') ?

                                                        (
                                                            <>
                                                                <li><p>SU</p></li>
                                                            </>
                                                        )

                                                        :

                                                        (
                                                            <>
                                                                <li className={styles.disable}><p>SU</p></li>
                                                            </>
                                                        )

                                                    }

                                                </ul>
                                            </div>
                                        </div>
                                    </div>
                                    <div className={styles.cardAddress}>
                                        <div className="cardDataTime">
                                            <h2>Address</h2>
                                            <div className={styles.dateTimeContent}>
                                                <p>{cardData?.address}</p>
                                            </div>
                                        </div>
                                    </div>
                                    <div className={styles.bottomButtonBox}>

                                        <ul>
                                            <li>
                                                <div className={styles.iconBox}>
                                                    <a href={`tel:+91${cardData?.contacts[0]?.contactNumber}`}>
                                                        <img src="/img/ecard/phone.png" alt="phone" className='img-fluid' />
                                                    </a>
                                                </div>
                                            </li>
                                            <li>
                                                <div className={styles.iconBox}>
                                                    <a href={`https://wa.me/+91${cardData?.contacts[1]?.contactNumber}?text=Hello ${cardData?.brandName}`} target="_blank">
                                                        <img src="/img/ecard/whatsapp.png" alt="whatsapp" className='img-fluid' />
                                                    </a>
                                                </div>
                                            </li>

                                            <li>
                                                <div className={`${styles.iconBox} ${styles.linkIcon}`}>
                                                    <img src="/img/ecard/linkBig.png" alt="link" className='img-fluid' />
                                                </div>
                                            </li>
                                            <li>
                                                <div className={styles.iconBox}>
                                                    <img src="/img/ecard/bizsicon.png" alt="mail" className='img-fluid' />
                                                </div>
                                            </li>
                                            <li>
                                                <div className={styles.iconBox} onClick={() => setActive(!active)}>
                                                    <img src="/img/ecard/back.png" alt="arow" className='img-fluid' />
                                                </div>
                                            </li>
                                        </ul>
                                    </div>
                                </div>
                                {/* =======share modal====== */}
                                <div className={isActive ? "shareModalBoxOpen" : "null"}>
                                    <div className={`${styles.iconBox} openShareModal`} onClick={handleModal}>
                                        <img src="/img/ecard/linkBig.png" alt="link" className='img-fluid' />
                                        <img src="/img/ecard/close.png" alt="link" className='img-fluid' />
                                    </div>
                                    <div className="shareModalBox">
                                        <ul>
                                            <li>
                                                <a href="#">

                                                    <img src="/img/ecard/chat.png" alt="arow" className='img-fluid' />

                                                </a>
                                            </li>
                                            {cardData?.socialLinks && cardData?.socialLinks?.map((curElt) => {
                                                return (
                                                    <>
                                                        {curElt.socialLinkType === "Facebook" &&
                                                            <li>
                                                                <a href={curElt.link} target="_blank">
                                                                    <div><img src="/img/ecard/link.png" alt="arow" className='img-fluid' /></div>
                                                                    <div>Facebook</div>
                                                                </a>
                                                            </li>

                                                        }
                                                        {curElt.socialLinkType === "Instagram" &&
                                                            <li>
                                                                <a href={curElt.link} target="_blank">

                                                                    <div><img src="/img/ecard/link.png" alt="arow" className='img-fluid' /></div>
                                                                    <div>Instagram</div>

                                                                </a>
                                                            </li>
                                                        }
                                                        {curElt.socialLinkType === "Youtube" &&
                                                            <li>
                                                                <a href={curElt.link} target="_blank">

                                                                    <div><img src="/img/ecard/link.png" alt="arow" className='img-fluid' /></div>
                                                                    <div>YouTube</div>

                                                                </a>
                                                            </li>
                                                        }
                                                        {curElt.socialLinkType === "LinkedIn" &&
                                                            <li>
                                                                <a href={curElt.link} target="_blank">

                                                                    <div><img src="/img/ecard/link.png" alt="arow" className='img-fluid' /></div>
                                                                    <div>Linkedin</div>

                                                                </a>
                                                            </li>

                                                        }
                                                        {curElt.socialLinkType === "Twitter" &&
                                                            <li>
                                                                <a href={curElt.link} target="_blank">
                                                                    <div><img src="/img/ecard/link.png" alt="arow" className='img-fluid' /></div>
                                                                    <div> Twitter</div>
                                                                </a>
                                                            </li>
                                                        }
                                                    </>
                                                )
                                            })}
                                            {cardData?.websiteLink &&

                                                <>
                                                    <li>
                                                        <a href={cardData?.websiteLink} target="_blank">
                                                            <div><img src="/img/ecard/link.png" alt="arow" className='img-fluid' /></div>
                                                            <div>Website</div>
                                                        </a>
                                                    </li>

                                                </>


                                            }
                                        </ul>
                                    </div>
                                </div>
                                {/* =======end====== */}
                            </div>

                        </div>
                        <div className='card_share_modal'>
                            <div className="offcanvas offcanvas-bottom" tabIndex="-1" id="offcanvasBottom" aria-labelledby="offcanvasBottomLabel" style={{ backgroundImage: `linear-gradient(to top, #${cardData?.theme?.dark} , #${cardData?.theme?.light})` }} >

                                <div className="offcanvas-body small">
                                    <div className={styles.share_card_content}>
                                        <h2>Share Via</h2>

                                        <div className={styles.share_media}>
                                            <ul>
                                                <li>
                                                    <a onClick={copy}>
                                                        <Image src="/img/cardIcon/copyClipboard.png" alt="copy_to_clipboard" width={35} height={35} />
                                                        <div className={styles.icon_name}>{!copied ? "Copy to clipboard" : "Copied!"}</div>
                                                    </a>
                                                </li>
                                                <li>
                                                    <a href={`https://www.facebook.com/sharer/sharer.php?u=${pageURL}${cardData?.user?._id}`}>
                                                        <Image src="/img/cardIcon/facebook.png" alt="facebook" width={35} height={35} />
                                                        <div className={styles.icon_name}>
                                                            Facebook
                                                        </div>
                                                    </a>
                                                </li>
                                                <li>
                                                    <a href={`whatsapp://send?text=${pageURL}${cardData?.user?._id}`}>
                                                        <Image src="/img/cardIcon/whatsapp.png" alt="whatsapp" width={35} height={35} />
                                                        <div className={styles.icon_name}>
                                                            Whatsapp
                                                        </div>
                                                    </a>
                                                </li>
                                                <li>
                                                    <a href={`https://twitter.com/intent/tweet?url=${pageURL}${cardData?.user?._id}`}>
                                                        <Image src="/img/cardIcon/twitter.png" alt="twitter" width={35} height={35} />
                                                        <div className={styles.icon_name}>
                                                            Twitter
                                                        </div>
                                                    </a>
                                                </li>

                                                <li>
                                                    <a href={`https://www.linkedin.com/sharing/share-offsite/?url=${pageURL}${cardData?.user?._id}`}>
                                                        <Image src="/img/cardIcon/linkedin.png" alt="linkedin" width={35} height={35} />
                                                        <div className={styles.icon_name}>
                                                            Linkedin
                                                        </div>
                                                    </a>
                                                </li>
                                                <li>
                                                    <a href={`https://telegram.me/share/url?url=${pageURL}${cardData?.user?._id}`}>
                                                        <Image src="/img/cardIcon/telegram.png" alt="telegram" width={35} height={35} />
                                                        <div className={styles.icon_name}>
                                                            Telegram
                                                        </div>
                                                    </a>
                                                </li>
                                            </ul>

                                        </div>
                                    </div>

                                </div>
                            </div>
                        </div>
                    </div>

                </div>
            </section>
        </>
    )
};



export async function getServerSideProps(context) {
    const id = context.query.id;
    console.log("iddddddddddd: ", id)
    const res = await fetch(`http://13.234.249.180:3001/api/business/card/${id}`)
    const data = await res.json()

    if (!data) {
        return {
            notFound: true,
        }
    }

    return {
        props: {
            data: data
        },
    }
}