import React, { useEffect, useState } from "react"
import Axios from "axios"
import { useRouter } from 'next/router'
import styles from '../../styles/BMCUserCard.module.css';
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import { faAngleRight, faAngleLeft, faLink } from "@fortawesome/free-solid-svg-icons";
import { faYoutube, faFacebook, faTwitter, faInstagram, faLinkedin } from "@fortawesome/free-brands-svg-icons";
import Image from "next/image";
import Link from "next/link";
import Head from 'next/head'
import { Swiper, SwiperSlide } from "swiper/react";

// Import Swiper styles
import "swiper/css";
import "swiper/css/effect-coverflow";
import "swiper/css/pagination";
// import required modules
import { EffectCoverflow, Pagination } from "swiper";

export default function UserCard(data) {
    

    const [cardData, setCardData] = useState()
    
    useEffect(() => {
        setCardData(data.data.data)
        console.log("cardData", cardData)
    }, [])
    

    const [active, setActive] = useState(false);


    return (
        <>
            <Head>
                <title>BMC | Business Management Card</title>
                <meta name="description" content="Generated by Bizsapp" />
                <link rel="icon" href="/favicon.ico" />
                {/* <meta name="msapplication-TileImage" content={properties.brandLogo} /> */}
                {/* <meta property="og:site_name" content={properties.brandName} /> */}
                {/* <meta property="og:BMC" content={properties.businessName} /> */}
                <meta property="og:title Card" content="Business Managment Card" />
                {/* <meta property="og:image" itemprop="image" content={properties.brandLogo} /> */}
                <meta property="og:type" content="website" />
                <meta property="og:image:type" content="image/png" />
                <meta property="og:image:width" content="300" />
                <meta property="og:image:height" content="300" />
                <meta property="og:url" content="https://bizsapp.com/" />
            </Head>



            <section className='container-fluid p-0'>
                <div className={styles.bmc_box}>
                    <div className={styles.flip_card}>
                        <div className={active ? `${styles.card} ${styles.active}` : styles.card}>
                            {/* fornt side */}
                            <div className={`${styles.card__face} ${styles.card__face_front}`} style={{backgroundImage: `linear-gradient(to top, #${cardData?.theme?.dark} , #${cardData?.theme?.light})`}}>
                                <div className={styles.cardFrontContent}>
                                    <div className={styles.cardName}>
                                        Business Management Card
                                    </div>

                                    <div className={styles.forntProfileBox}>
                                        <div className={styles.companyLogo}>
                                            <img src="" className="img-fluid" />
                                        </div>
                                        <div className={styles.companyName}>
                                            <h1>Himanshu Sharma</h1>
                                        </div>
                                        <div className={styles.designationName}>
                                            <span>(Software Developer)</span>
                                        </div>
                                        <div className={styles.descriptionBox}>
                                            <p>A designation is a description, name, or title that is given to someone or something. Designation is the fact of giving that description, name, or title</p>
                                        </div>
                                    </div>

                                    <div className={styles.catalogBox}>
                                        <div className={styles.catalogTitle}>
                                            <div>Our Products</div>
                                        </div>
                                        <div className="catalogSlider">
                                            <Swiper
                                                slidesPerView={"auto"}
                                                spaceBetween={20}
                                                pagination={{
                                                    clickable: true,
                                                }}
                                                modules={[Pagination]}
                                                className="mySwiper"
                                            >
                                                <SwiperSlide>
                                                    <div className={styles.prouctSliderBox}>
                                                        <div className={styles.productImg}>
                                                            <img src='/img/ecard/product1.png' alt='catalog_image' className='img-fluid' />
                                                        </div>
                                                        <div className={styles.productName}>
                                                            Women's Slim Fit washed jeans strectchable
                                                        </div>
                                                    </div>
                                                </SwiperSlide>
                                                <SwiperSlide>
                                                    <div className={styles.prouctSliderBox}>
                                                        <div className={styles.productImg}>
                                                            <img src='/img/ecard/product2.png' alt='catalog_image' className='img-fluid' />
                                                        </div>
                                                        <div className={styles.productName}>
                                                            Women's Slim Fit washed jeans strectchable
                                                        </div>
                                                    </div>
                                                </SwiperSlide>
                                                <SwiperSlide>
                                                    <div className={styles.prouctSliderBox}>
                                                        <div className={styles.productImg}>
                                                            <img src='/img/ecard/product3.png' alt='catalog_image' className='img-fluid' />
                                                        </div>
                                                        <div className={styles.productName}>
                                                            Women's Slim Fit washed jeans strectchable
                                                        </div>
                                                    </div>
                                                </SwiperSlide>
                                                <SwiperSlide>
                                                    <div className={styles.prouctSliderBox}>
                                                        <div className={styles.productImg}>
                                                            <img src='/img/ecard/product4.png' alt='catalog_image' className='img-fluid' />
                                                        </div>
                                                        <div className={styles.productName}>
                                                            Women's Slim Fit washed jeans strectchable
                                                        </div>
                                                    </div>
                                                </SwiperSlide>
                                            </Swiper>
                                        </div>
                                    </div>

                                    <div className={styles.bottomButtonBox}>
                                        <ul>
                                            <li>
                                                <div className={styles.iconBox}>
                                                    <img src="/img/catalog/link.png" alt="link" className='img-fluid' />
                                                </div>
                                            </li>
                                            <li>
                                                <div className={styles.iconBox}>
                                                    <img src="/img/catalog/phone.png" alt="phone" className='img-fluid' />
                                                </div>
                                            </li>
                                            <li>
                                                <div className={styles.iconBox}>
                                                    <img src="/img/catalog/whatsapp.png" alt="whatsapp" className='img-fluid' />
                                                </div>
                                            </li>
                                            <li>
                                                <div className={styles.iconBox}>
                                                    <img src="/img/catalog/mail.png" alt="mail" className='img-fluid' />
                                                </div>
                                            </li>
                                            <li>
                                                <div className={styles.iconBox} onClick={() => setActive(!active)}>
                                                    <img src="/img/catalog/arow.png" alt="arow" className='img-fluid' />
                                                </div>
                                            </li>
                                        </ul>
                                    </div>
                                </div>
                            </div>
                            {/* back side */}
                            <div className={`${styles.card__face} ${styles.card__face_back}`}>
                                <div className={styles.clickButton} onClick={() => setActive(!active)}>
                                    <FontAwesomeIcon icon={faAngleLeft} />
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </section>
        </>
    )
};

export async function getServerSideProps(context){
    const id = context.query.id;
    console.log("iddddddddddd: ", id)
    const res = await fetch(`http://13.234.249.180:3001/api/business/card/${id}`)
    const data = await res.json()

    if(!data){
        return{
            notFound: true,
        }
    }

    return {
        props: {
            data: data
        },
    }
}
