import React, { useEffect, useState } from "react"
import Axios from "axios"
import { useRouter } from 'next/router'
import styles from '../../styles/BMCUserCard.module.css';
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import { faAngleRight, faAngleLeft, faLink } from "@fortawesome/free-solid-svg-icons";
import { faYoutube, faFacebook, faTwitter, faInstagram, faLinkedin } from "@fortawesome/free-brands-svg-icons";
import Image from "next/image";
import Link from "next/link";
import Head from 'next/head'
import { Swiper, SwiperSlide } from "swiper/react";

// Import Swiper styles
import "swiper/css";
import "swiper/css/effect-coverflow";
import "swiper/css/pagination";
// import required modules
import { EffectCoverflow, Pagination } from "swiper";
import ReactPlayer from 'react-player'

export default function UserCard(data) {


    const [cardData, setCardData] = useState()

    useEffect(() => {
        setCardData(data.data.data)
        console.log("cardData", cardData)
    }, [])


    const [active, setActive] = useState(false);
    const [isActive, setIsActive] = useState("false")

    const handleModal = () => {
        setIsActive(!isActive)
    }


    return (
        <>
            <Head>
                <title>BMC | Business Management Card</title>
                <meta name="description" content="Generated by Bizsapp" />
                <link rel="icon" href="/favicon.ico" />
                {/* <meta name="msapplication-TileImage" content={properties.brandLogo} /> */}
                {/* <meta property="og:site_name" content={properties.brandName} /> */}
                {/* <meta property="og:BMC" content={properties.businessName} /> */}
                <meta property="og:title Card" content="Business Managment Card" />
                {/* <meta property="og:image" itemprop="image" content={properties.brandLogo} /> */}
                <meta property="og:type" content="website" />
                <meta property="og:image:type" content="image/png" />
                <meta property="og:image:width" content="300" />
                <meta property="og:image:height" content="300" />
                <meta property="og:url" content="https://bizsapp.com/" />
            </Head>



            <section className='container-fluid p-0'>
                <div className={styles.bmc_box}>
                    <div className={styles.flip_card}>
                        <div className={active ? `${styles.card} ${styles.active}` : styles.card}>
                            {/* fornt side */}
                            <div className={`${styles.card__face} ${styles.card__face_front}`} style={{ backgroundImage: `linear-gradient(to top, #${cardData?.theme?.dark} , #${cardData?.theme?.light})` }}>
                                <div className={styles.cardFrontContent}>
                                    <div className={styles.cardName}>
                                        Business Management Card
                                    </div>

                                    <div className={styles.forntProfileBox}>
                                        <div className={styles.companyLogo}>
                                            <img src={cardData?.brandLogo} className="img-fluid" />
                                        </div>
                                        <div className={styles.companyName}>
                                            <h1>{cardData?.brandName}</h1>
                                        </div>
                                        <div className={styles.designationName}>
                                            <span>({cardData?.user?.title})</span>
                                        </div>
                                        <div className={styles.descriptionBox}>
                                            <p>{cardData?.about}</p>
                                        </div>
                                    </div>

                                    <div className={styles.catalogBox}>
                                        <div className={styles.catalogTitle}>
                                            <div>Our Products</div>
                                        </div>
                                        <div className="catalogSlider">
                                            <Swiper
                                                slidesPerView={"auto"}
                                                spaceBetween={20}
                                                pagination={{
                                                    clickable: true,
                                                }}
                                                modules={[Pagination]}
                                                className="mySwiper"
                                            >
                                                {cardData?.products && cardData?.products?.map((curElt) => {
                                                    return (
                                                        <>
                                                            <SwiperSlide>
                                                                <div className={styles.prouctSliderBox}>
                                                                    <div className={styles.productImg}>
                                                                        {curElt.images && curElt.images?.map((productImg) => {
                                                                            return (
                                                                                <>
                                                                                    <img src={productImg.location} alt='catalog_image' className='img-fluid' />
                                                                                </>
                                                                            )
                                                                        })}
                                                                        {/* <img src='/img/ecard/product1.png' alt='catalog_image' className='img-fluid' /> */}
                                                                    </div>
                                                                    <div className={styles.productName}>
                                                                        {curElt.title}
                                                                    </div>
                                                                </div>
                                                            </SwiperSlide>
                                                        </>
                                                    )
                                                })}
                                            </Swiper>
                                        </div>
                                    </div>

                                    <div className={styles.bottomButtonBox}>

                                        <ul>
                                            <li>
                                                <div className={styles.iconBox}>
                                                    <a href={`https://wa.me/+91${cardData?.contacts[1]?.contactNumber}?text=Hello ${cardData?.brandName}`} target="_blank">
                                                        <img src="/img/ecard/whatsapp.png" alt="whatsapp" className='img-fluid' />
                                                    </a>
                                                </div>
                                            </li>
                                            <li>
                                                <div className={styles.iconBox}>
                                                    <a href={`tel:+91${cardData?.contacts[0]?.contactNumber}`}>
                                                        <img src="/img/ecard/phone.png" alt="phone" className='img-fluid' />
                                                    </a>
                                                </div>
                                            </li>
                                            <li>
                                                <div className={`${styles.iconBox}  ${styles.linkIcon}`}>
                                                    <img src="/img/ecard/link.png" alt="link" className='img-fluid' />
                                                </div>
                                            </li>
                                            <li>
                                                <div className={styles.iconBox}>
                                                    <img src="/img/ecard/bizsicon.png" alt="mail" className='img-fluid' />
                                                </div>
                                            </li>
                                            <li>
                                                <div className={styles.iconBox} onClick={() => setActive(!active)}>
                                                    <img src="/img/ecard/next.png" alt="arow" className='img-fluid' />
                                                </div>
                                            </li>
                                        </ul>
                                    </div>
                                </div>
                                {/* =======share modal====== */}
                                <div className={!isActive ? "shareModalBoxOpen" : "null"}>
                                    <div className={`${styles.iconBox} openShareModal`} onClick={handleModal}>
                                        <img src="/img/ecard/link.png" alt="link" className='img-fluid' />
                                        <img src="/img/ecard/close.png" alt="link" className='img-fluid' />
                                    </div>
                                    <div className="shareModalBox">
                                        <ul>
                                            <li>
                                                <a href="#">

                                                    <img src="/img/ecard/chat.png" alt="arow" className='img-fluid' />

                                                </a>
                                            </li>
                                            {cardData?.socialLinks && cardData?.socialLinks?.map((curElt) => {
                                                return (
                                                    <>
                                                        {curElt.socialLinkType === "Facebook" &&
                                                            <li>
                                                                <a href={curElt.link} target="_blank">
                                                                    <img src="/img/ecard/link.png" alt="arow" className='img-fluid' />
                                                                    Facebook
                                                                </a>
                                                            </li>

                                                        }
                                                        {curElt.socialLinkType === "Instagram" &&
                                                            <li>
                                                                <a href={curElt.link} target="_blank">

                                                                    <img src="/img/ecard/link.png" alt="arow" className='img-fluid' />
                                                                    Instagram

                                                                </a>
                                                            </li>
                                                        }
                                                        {curElt.socialLinkType === "Youtube" &&
                                                            <li>
                                                                <a href={curElt.link} target="_blank">

                                                                    <img src="/img/ecard/link.png" alt="arow" className='img-fluid' />
                                                                    YouTube

                                                                </a>
                                                            </li>
                                                        }
                                                        {curElt.socialLinkType === "LinkedIn" &&
                                                            <li>
                                                                <a href={curElt.link} target="_blank">

                                                                    <img src="/img/ecard/link.png" alt="arow" className='img-fluid' />
                                                                    Linkedin

                                                                </a>
                                                            </li>

                                                        }
                                                        {curElt.socialLinkType === "Twitter" &&
                                                            <li>
                                                                <a href={curElt.link} target="_blank">
                                                                    <img src="/img/ecard/link.png" alt="arow" className='img-fluid' />
                                                                    Twitter
                                                                </a>
                                                            </li>
                                                        }
                                                    </>
                                                )
                                            })}
                                            {cardData?.websiteLink &&

                                                <li>
                                                    <a href={cardData?.websiteLink} target="_blank">
                                                        <img src="/img/ecard/link.png" alt="arow" className='img-fluid' />
                                                        Website
                                                    </a>
                                                </li>

                                            }
                                        </ul>
                                    </div>
                                </div>
                                {/* =======end====== */}
                            </div>
                            {/* back side */}
                            <div className={`${styles.card__face} ${styles.card__face_back}`} style={{ backgroundImage: `linear-gradient(to top, #${cardData?.theme?.dark} , #${cardData?.theme?.light})` }}>
                                <div className={styles.cardBackContent}>
                                    <div className={styles.cardName}>
                                        Business Management Card
                                    </div>
                                    <div className={styles.cardVideoBox}>
                                        <div className="cardVideo">
                                            <ReactPlayer 
                                                url={cardData?.brandVideo?.location} 
                                                controls
                                                config={{ file: { attributes: { controlsList: 'nodownload' } } }}
                                                onContextMenu={(e) => e.preventDefault()}
                                            />
                                        </div>
                                    </div>
                                    <div className={styles.cardDateTimeBox}>
                                        
                                    </div>
                                    <div className={styles.cardAddress}>

                                    </div>
                                    <div className={styles.bottomButtonBox}>

                                        <ul>
                                            <li>
                                                <div className={styles.iconBox}>
                                                    <a href={`https://wa.me/+91${cardData?.contacts[1]?.contactNumber}?text=Hello ${cardData?.brandName}`} target="_blank">
                                                        <img src="/img/ecard/whatsapp.png" alt="whatsapp" className='img-fluid' />
                                                    </a>
                                                </div>
                                            </li>
                                            <li>
                                                <div className={styles.iconBox}>
                                                    <a href={`tel:+91${cardData?.contacts[0]?.contactNumber}`}>
                                                        <img src="/img/ecard/phone.png" alt="phone" className='img-fluid' />
                                                    </a>
                                                </div>
                                            </li>
                                            <li>
                                                <div className={`${styles.iconBox} ${styles.linkIcon}`}>
                                                    <img src="/img/ecard/link.png" alt="link" className='img-fluid' />
                                                </div>
                                            </li>
                                            <li>
                                                <div className={styles.iconBox}>
                                                    <img src="/img/ecard/bizsicon.png" alt="mail" className='img-fluid' />
                                                </div>
                                            </li>
                                            <li>
                                                <div className={styles.iconBox} onClick={() => setActive(!active)}>
                                                    <img src="/img/ecard/back.png" alt="arow" className='img-fluid' />
                                                </div>
                                            </li>
                                        </ul>
                                    </div>
                                </div>
                                {/* =======share modal====== */}
                                <div className={!isActive ? "shareModalBoxOpen" : "null"}>
                                    <div className={`${styles.iconBox} openShareModal`} onClick={handleModal}>
                                        <img src="/img/ecard/link.png" alt="link" className='img-fluid' />
                                        <img src="/img/ecard/close.png" alt="link" className='img-fluid' />
                                    </div>
                                    <div className="shareModalBox">
                                        <ul>
                                            <li>
                                                <a href="#">

                                                    <img src="/img/ecard/chat.png" alt="arow" className='img-fluid' />

                                                </a>
                                            </li>
                                            {cardData?.socialLinks && cardData?.socialLinks?.map((curElt) => {
                                                return (
                                                    <>
                                                        {curElt.socialLinkType === "Facebook" &&
                                                            <li>
                                                                <a href={curElt.link} target="_blank">
                                                                    <img src="/img/ecard/link.png" alt="arow" className='img-fluid' />
                                                                    Facebook
                                                                </a>
                                                            </li>

                                                        }
                                                        {curElt.socialLinkType === "Instagram" &&
                                                            <li>
                                                                <a href={curElt.link} target="_blank">

                                                                    <img src="/img/ecard/link.png" alt="arow" className='img-fluid' />
                                                                    Instagram

                                                                </a>
                                                            </li>
                                                        }
                                                        {curElt.socialLinkType === "Youtube" &&
                                                            <li>
                                                                <a href={curElt.link} target="_blank">

                                                                    <img src="/img/ecard/link.png" alt="arow" className='img-fluid' />
                                                                    YouTube

                                                                </a>
                                                            </li>
                                                        }
                                                        {curElt.socialLinkType === "LinkedIn" &&
                                                            <li>
                                                                <a href={curElt.link} target="_blank">

                                                                    <img src="/img/ecard/link.png" alt="arow" className='img-fluid' />
                                                                    Linkedin

                                                                </a>
                                                            </li>

                                                        }
                                                        {curElt.socialLinkType === "Twitter" &&
                                                            <li>
                                                                <a href={curElt.link} target="_blank">
                                                                    <img src="/img/ecard/link.png" alt="arow" className='img-fluid' />
                                                                    Twitter
                                                                </a>
                                                            </li>
                                                        }
                                                    </>
                                                )
                                            })}
                                            {cardData?.websiteLink &&

                                                <li>
                                                    <a href={cardData?.websiteLink} target="_blank">
                                                        <img src="/img/ecard/link.png" alt="arow" className='img-fluid' />
                                                        Website
                                                    </a>
                                                </li>

                                            }
                                        </ul>
                                    </div>
                                </div>
                                {/* =======end====== */}
                            </div>
                        </div>


                    </div>


                </div>
            </section>
        </>
    )
};

export async function getServerSideProps(context) {
    const id = context.query.id;
    console.log("iddddddddddd: ", id)
    const res = await fetch(`http://13.234.249.180:3001/api/business/card/${id}`)
    const data = await res.json()

    if (!data) {
        return {
            notFound: true,
        }
    }

    return {
        props: {
            data: data
        },
    }
}
