import Head from 'next/head'
import Footer from './includes/Footer';
import Navigation from "./includes/Navigation";


export default function branding() {
    return(
        <>
            <Head>
                <title>BizsApp</title>
                <meta name="description" content="Generated by Bizsapp" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Navigation />
            <Footer />
        </>
    )
};
