import Head from 'next/head'
import Footer from './includes/Footer';
import Navigation from "./includes/Navigation";
import BeforeFooter from "./includes/BeforeFooter";
import Header from './about/Header';
import PageBody from './about/PageBody';


export default function branding() {
    return(
        <>
            <Head>
                <meta name="description" content="Generated by Bizsapp" />
                <link rel="icon" href="/img/favicon.svg" />
                <title>BizsApp | The Business App</title>
            </Head>

            <Navigation />
            <Header />
            <PageBody />
            <BeforeFooter />
            <Footer />
        </>
    )
};
