import Head from 'next/head'
import Content from './branding/Content';
import Header from './branding/Header';
import FeatureFooter from './includes/BeforeFooter';
import ColorPalette from './includes/ColorPalette';
import Footer from './includes/Footer';
import Navigation from "./includes/Navigation";


export default function branding() {
    return(
        <>
            <Head>
                <title>BizsApp</title>
                <meta name="description" content="Generated by Bizsapp" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <Navigation />
            <Header />
            <Content />
            <ColorPalette />
            <FeatureFooter />
            <Footer />
        </>
    )
};
