import Head from 'next/head'
import Navigation from "./includes/Navigation";
import Footer from "./includes/Footer";
import Header from './Features/Header';
import FeatureBody from './Features/FeatureBody';
import BeforeFooter from "./includes/BeforeFooter";

export default function features() {
    return(
        <>
            <Head>
                <meta name="description" content="Generated by Bizsapp" />
                <link rel="icon" href="/img/favicon.svg" />
                <title>BizsApp | The Business App</title>
            </Head>
            <Navigation />
            <Header />
            <FeatureBody />
            <BeforeFooter />
            <Footer />
        </>
    )
};
