import Head from 'next/head'
import Navigation from "./includes/Navigation";
import Body from './help_center/Body';
import Footer from "./includes/Footer";



export default function help_center() {
    return(
        <>
            <Head>
                <meta name="description" content="Generated by Bizsapp" />
                <link rel="icon" href="/img/favicon.svg" />
                <title>BizsApp | The Business App</title>
            </Head>
            <Navigation />
            <Body />
            <Footer />
        </>
    )
};
